### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by mo-shaz** [greguz/fastify-no-additional-properties#12]
Hey, I'm new to Fastify, TypeScript and even GitHub (this is my first issue ever). This might be a small TS issue, but it would be so much helpful if you could help me resolve it.

I installed your package and is importing it using ESM syntax (because I specified it both in the package.json and tsconfig.json, and if I use commonjs everything starts to break) and the compiler throws an error regarding the type declaration of the module.

<code>
Could not find a declaration file for module 'fastify-no-additional-properties'. 'server/node_modules/fastify-no-additional-propertie    s/index.js' implicitly has an 'any' type.

Try `npm i --save-dev @types/fastify-no-additional-properties` if it exists or add a new declaration (.d.ts) file containing `declare module 'fastify-no-addition    al-properties';`
</code>

And I couldn't find it via npm nor can write a <code>.d.ts</code> file myself. It would be really great if you could help. Thanks.

**Comment by mo-shaz** [comment]
Just found out about <code>@ts-ignore</code>.
Closing the issue, Thanks anyways.

**Comment by zachazar** [comment]
@mo-shaz I created types locally that you're welcome to add to your project.
