### ISSUE TITLE
The plugin doesn't work with Ref's

### ISSUE THREAD

**Issue by billomore** [greguz/fastify-no-additional-properties#15]
Hi guys, 

Great idea for a plugin! The default behavior is a freaking security breach, and I wish `additionalProperties: false` would be default for Fastify.

The problem I had while using the plugin though, is that it doesn't work with [shared schemas](https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/#adding-a-shared-schema) - `Ref`s. Also, it's possibly doesn't work with [unions](https://json-schema.org/understanding-json-schema/reference/combining#anyof) (didn't check this one though).

So, inspired by your code, came up with the following:
```typescript
fastify.addHook('onRoute', route => {
    const fixObject = (schema: any) => {
       // additionalPrperties only applies to objects
        if (schema.type === 'object') {
            schema.additionalProperties = false;
        }
    }
    const hardenSchema = (schema: any) => {
        // in case of Ref, retrieve the actual schema
        if (schema.$ref) {
            schema = fastify.getSchema(schema.$ref) as any;
        }
        // in case of union, go through all possibilities and fix them
        if (schema.anyOf && schema.anyOf.length) {
            for (const unionMember of schema.anyOf) {
                fixObject(unionMember);
            }
        } else {
            fixObject(schema);
        }
    }
    if (route.schema) {
        if (route.schema.body) {
            hardenSchema(route.schema.body)
        }
        if (route.schema.params) {
            hardenSchema(route.schema.params)
        }
        if (route.schema.querystring) {
            hardenSchema(route.schema.querystring)
        }
    }
});
```

Adding `additionalProperties: false` to the response schemas is not required as Fastify anyways cuts all the additional properties while serializing the response.

Maybe it'll be helpful to some :)

**Comment by greguz** [comment]
Hey @billomore, thank you for the nice words, I also hate by-design security breaches.

Your approach is nice, but if you reuse multiple times the same `$ref`, the same schema will be updated multiple times.

I think a better approach is to `for each` all registered schema and update those just one time before server start. This will be a new option like `updateSharedSchema` or something like that.

About the response schema, I had some strange behaviour with Fastify and response properties without `additionalProperties: false`. This was probably an old bug or something like that. I'll deprecated the `response` option and add you comment (thank you!).

**Comment by greguz** [comment]
Actually, after some testing, I think your approach could be the most effective one. Are you interested to do a PR? @billomore

**Comment by billomore** [comment]
hi, sorry for a long response. Unfortunately I don't have a spare minute these days, but feel free to use my code - it works fine except the case with unions of unions, must be recursive to handle it.
