### ISSUE TITLE
Purpose missing in doc

### ISSUE THREAD

**Issue by niksmac** [greguz/fastify-no-additional-properties#5]
It would be good if you can add why use this plugin in the readme.

**Comment by greguz** [comment]
You're right :) I'll add some words in the next update.

**Comment by greguz** [comment]
Just added [some words](https://github.com/greguz/fastify-no-additional-properties/blob/master/README.md). Do you think It's more understandable now @niksmac?

**Comment by niksmac** [comment]
Thanks
