### ISSUE TITLE
Iterate over response schemas?

### ISSUE THREAD

**Issue by jonasfj** [greguz/fastify-no-additional-properties#7]
As reported in #5 the purpose isn't really given in the readme :D

But I'm guessing the idea is that I don't have to write `additionalProperties: false` in all schemas. So maybe we should also support adding it on output schemas. Sometimes it's preferable to simply fail when an invariant is violated.

**Comment by greguz** [comment]
And then, after some months... [Tadaaaa](https://github.com/greguz/fastify-no-additional-properties/commit/ce34e5bc3401ec0f28027159aa5b05eda564b4c5)!

**Comment by greguz** [comment]
Published with the [last version](https://www.npmjs.com/package/fastify-no-additional-properties).
